# If you need to override keymap, use these args (don't forget to change values to yours):
# cmake-args: -DKEYMAP_FILE=../../config/sofle_60.keymap
# artifact-name: sofle_60_left-nice_nano_v2-zmk

include:
  # main layout
  - board: nice_nano_v2
    shield: sofle_left
  - board: nice_nano_v2
    shield: sofle_right

  # debug layout
  - board: nice_nano_v2
    shield: sofle_left
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: sofle_right
    snippet: zmk-usb-logging

  # reset board
  - board: nice_nano_v2
    shield: settings_reset
