# To override keymap path:
# cmake-args: -DKEYMAP_FILE=../../config/sofle_60.keymap
# To override artifact name:
# artifact-name: sofle_60_left-nice_nano-zmk

include:
  # main layout
  - board: nice_nano
    shield: sofle_left
    artifact-name: sofle_left
  - board: nice_nano
    shield: sofle_right
    artifact-name: sofle_right

  # debug layout
  - board: nice_nano
    shield: sofle_left
    snippet: zmk-usb-logging
    artifact-name: sofle_debug_left
  - board: nice_nano
    shield: sofle_right
    snippet: zmk-usb-logging
    artifact-name: sofle_debug_right

  # reset board
  - board: nice_nano
    shield: settings_reset
