include:
  # 60 (full) key layout
  - board: nice_nano_v2
    shield: sofle_left
    cmake-args: -DKEYMAP_FILE=../../config/sofle_60.keymap
    artifact-name: sofle_60_left-nice_nano_v2-zmk
  - board: nice_nano_v2
    shield: sofle_right
    cmake-args: -DKEYMAP_FILE=../../config/sofle_60.keymap
    artifact-name: sofle_60_right-nice_nano_v2-zmk

  # 36 key layout
  - board: nice_nano_v2
    shield: sofle_left
    cmake-args: -DKEYMAP_FILE=../../config/sofle_36.keymap
    artifact-name: sofle_36_left-nice_nano_v2-zmk
  - board: nice_nano_v2
    shield: sofle_right
    cmake-args: -DKEYMAP_FILE=../../config/sofle_36.keymap
    artifact-name: sofle_36_right-nice_nano_v2-zmk

  # debug layout
  - board: nice_nano_v2
    shield: sofle_left
    cmake-args: -DKEYMAP_FILE=../../config/sofle_60.keymap
    artifact-name: sofle_debug_left-nice_nano_v2-zmk
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: sofle_right
    cmake-args: -DKEYMAP_FILE=../../config/sofle_60.keymap
    artifact-name: sofle_debug_right-nice_nano_v2-zmk
    snippet: zmk-usb-logging

  # 34 key layout
  - board: nice_nano_v2
    shield: sofle_left
    cmake-args: -DKEYMAP_FILE=../../config/sofle_34.keymap
    artifact-name: sofle_34_left-nice_nano_v2-zmk
  - board: nice_nano_v2
    shield: sofle_right
    cmake-args: -DKEYMAP_FILE=../../config/sofle_34.keymap
    artifact-name: sofle_34_right-nice_nano_v2-zmk

  # reset board
  - board: nice_nano_v2
    shield: settings_reset
